### ISSUE TITLE
No volume controls in HomeKit?

### ISSUE THREAD

**Issue by rkrug** [homebridge-squeezebox/homebridge-squeezebox#15]
Hi

I git the on / off switch working, but also would like to have the possibility to increase / decrease the volume. Is this possible in HomeKit?

Also, is this still maintained?

Thanks,

Rainer

**Comment by greebowarrior** [comment]
Hi Rainer,

Sorry, I no longer have any Squeezebox hardware, and so this project isn't maintained anymore :(

**Comment by rkrug** [comment]
OK. Thanks anyway.
