### ISSUE TITLE
Seeking new maintainer

### ISSUE THREAD

**Issue by greebowarrior** [homebridge-squeezebox/homebridge-squeezebox#16]
Due to the fact I no longer own any Squeezebox hardware, I'm not really able to maintain this project any more, so I'm looking for someone who could take over.

Please let me know if you're interested, and I could see about transferring ownership of the repo

**Comment by leematt** [comment]
I have three Squeezebox devices and have been using this plugin for a couple of years, albeit with some changes I made for caching the accessories in Homebridge. I'd been meaning to publish my version and maybe issue a pull request, but hadn't fully worked out some kinks and don't know the Homebridge platform very well.

If no one more capable wants to take over, I could do so. As I am still using Squeezebox devices and sort of maintaining the code for myself, and have been interested in further updates for stability and functionality, I might be able to keep things running for a bit longer. 🙂

**Comment by rkrug** [comment]
@leemat: out of curiosity - do you have volume control as well?

**Comment by leematt** [comment]
> out of curiosity - do you have volume control as well?

Very limited. I am just using the volume characteristic that is already in the plugin, and using a HomeKit app that supports that custom characteristic to add volume levels to scenes. So, I can have a scene set all the players to 30% volume, but can't tell Siri to change the volume beyond that. I want to add full volume support if/when possible.

**Comment by rkrug** [comment]
OK. That explains. I was only looking into the Home app. Now I looked into the Home+ app, and there is the volume...

Have you seen https://github.com/Supereg/homebridge-http-speaker ? This could be an option, and supported by the Home app as well.

**Comment by leematt** [comment]
Unfortunately I've recently suffered a couple of hardware failures on my Squeezebox devices and am no longer using or maintaining them. I may revisit them at some point, but am currently focused on replacing them.

**Comment by rkrug** [comment]
I know absolutely nothing about node and javascript and the whole home bridge plugin is completely foreign to me, but I forked the repo (https://github.com/rkrug/homebridge-squeezebox) and implemented the players as fans, so that I now can control the volume (speed) via Siri or in automations.

So - how should this be taken forward? Suggestions?

**Comment by okonet** [comment]
What does everyone thinks of creating an organization for it instead so multiple people could be responsible for maintaining it? I think transferring to another single person account will lead to a similar situation in the long term.

This strategy worked well for me with [react-dropzone](https://github.com/react-dropzone/react-dropzone/) repo.

Another thing I could setup right after is automatic release process so the contribution are made even more simple and do not require maintainer to do additional work besides code review and merging PRs with semantic versioning in mind.

**Comment by rkrug** [comment]
Fine with me.

**Comment by okonet** [comment]
So the problem I'm trying to prevent is this: https://github.com/greebowarrior/homebridge-squeezebox/pull/11#issuecomment-469559364 where I had to publish my fork under a separate package on NPM because the PR was never released.

**Comment by rkrug** [comment]
I have done the same with implementing fans instead of lights (volume control from HomeKit) https://github.com/rkrug/homebridge-squeezebox 
. Why don't you set up an organisation, and I'll join. Warning: I know nothing about javaScript.

**Comment by okonet** [comment]
@greebowarrior what do you think about creating an organization for this plugin?
