### ISSUE TITLE
Volume?

### ISSUE THREAD

**Issue by simonrb2000** [homebridge-squeezebox/homebridge-squeezebox#4]
Hi there,

Not really an issue, was curious to know what this plugin can do before install it. I can currently control power states using edomoticz. Does this control volume? That would be handy! 
Cheers

**Comment by greebowarrior** [comment]
Yes it does :)

**Comment by simonrb2000** [comment]
Brilliant, I have just tried it and I can only get the volume through EVE app. I use the native app within iOS 10 and on the watchOS 3. Is there a way to make them work with the stock Home app? The power works fine though 👍

**Comment by greebowarrior** [comment]
I'll take a look, I haven't tested it with Home in iOS 10 yet

**Comment by simonrb2000** [comment]
Cheers mate.

Sent from my iPhone

On 8 Oct 2016, at 12:46, Martin Purcell <notifications@github.com<mailto:notifications@github.com>> wrote:

I'll take a look, I haven't tested it with Home in iOS 10 yet

##

**Comment by PatchworkBoy** [comment]
HomeKit spec doesn't have a suitable service type that supports volume and power characteristics... it'd have to create a custom service type (as it currently does), thus out of spec, thus unsupported by native-spec-only apps such as iOS10 Home client.

**Comment by simonrb2000** [comment]
Could it not be like a dimmer that relates to volume? It's what I'm using with my Denon amp? Or two switches, one called conservatory radio and conservatory radio volume. Then asking Siri to "turn off the Conservatory Radio" would turn off the radio and "set Conservatory radio volume to 50%" would do just that?

Cheers

On 9 Oct 2016, at 10:26, Marci <notifications@github.com<mailto:notifications@github.com>> wrote:

HomeKit spec doesn't have a suitable service type that supports volume and power characteristics... it'd have to create a custom service type (as it currently does), thus out of spec, thus unsupported by native-spec-only apps such as iOS10 Home client.

##

**Comment by PatchworkBoy** [comment]
Yep, but it'd have to show up as a dimmer, and a switch. Two separate devices, not a combined device.

**Comment by PatchworkBoy** [comment]
Oh, yes... author needs to just map the LMS as a regular dimmable light rather than a custom device with a custom characteristic, then change it's category to media device. That's the only way it'd work in a spec-only app. Could have a flag in config.json that switches from map-to-spec-only to use-custom-chars to allow folks to choose and allow support either way.

**Comment by simonrb2000** [comment]
Any luck on this mate? Chumping at the bits to be able to change volume on my squeezeboxes via Siri :)

**Comment by simonrb2000** [comment]
I setup virtual dimmers within domoticz and they now get/set the volume and power states.
