### ISSUE TITLE
syntax error?

### ISSUE THREAD

**Issue by fireheadman** [homebridge-squeezebox/homebridge-squeezebox#6]

**Comment by fireheadman** [comment]
"platforms": [
        {
            "platform": "Squeezebox",
            "name": "Squeezebox",
            "host": "127.0.0.1",
            "port": 9000
        }
    }

SHouldn't it be....

    "platforms": [
        {
            "platform": "Squeezebox",
            "name": "Squeezebox",
            "host": "127.0.0.1",
            "port": 9000
        }
    ]       <----Right Bracket vs Right Curly Brace???

**Comment by rkrug** [comment]
True. Thanks.

**Comment by rkrug** [comment]
Is fixed in the dev branch.
