### ISSUE TITLE
Plugin blocks homebridge when Logitech Media Server is offline

### ISSUE THREAD

**Issue by naofireblade** [homebridge-squeezebox/homebridge-squeezebox#8]
As long as the LMS is running everything works fine. But when its powered off, the complete homebridge seems to be blocked. I cant communicate with any other device on homebridge.

**Comment by rkrug** [comment]
Late reply.

I have no solution for this, but you can run individual instances for individual plugins in homebridge: See https://github.com/homebridge/homebridge/wiki/Child-Bridges for details. 

But this is definitely an issue which should be addressed.

**Comment by rkrug** [comment]
At the moment, I am running each homebridge plugin in a separate homebridge child instance - not ideal, but it works. But we should look into this.

**Comment by mark3206** [comment]
I've also just encountered a slight variation of this problem. If the ip or port address for the LMS is incorrect, it has the same impact - blocks homebridge.  (in my situation the LMS had a dynamic IP address that not surprisingly changed after it was restarted)

**Comment by rkrug** [comment]
I have no solution. As I said above, the (suboptimal) solution is to run home bridge-squeezebox in an individual child bridge as in this case not the whole home bridge hangs (I am running for each plugin a child bridge).

I would suggest to use either fixed IPs (you should be able to set them in your DHCP server (Router), or they the hostname instead.

I will close this issue, as I do not think I will fix it.
